apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions-service
  template:
    metadata:
      labels:
        app: transactions-service
    spec:
      containers:
      - name: transactions-service
        image: hlaingminpaing/transactions-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials-secret
              key: DB_PASSWORD
        - name: DB_NAME
          value: "digital_wallet"
---
apiVersion: v1
kind: Service
metadata:
  name: transactions-service
spec:
  selector:
    app: transactions-service
  ports:
    - name: http
      protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
