apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
      - name: wallet-service
        image: hlaingminpaing/poc-digital-wallet-app:wallet-service
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials-secret
              key: DB_PASSWORD
        - name: DB_NAME
          value: "digital_wallet"
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  selector:
    app: wallet-service
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
